FROM java:8
EXPOSE 8983
ADD /target/fhir-practitioner-client-service-0.0.1-SNAPSHOT.jar fhir-practitioner-client-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","fhir-practitioner-client-service-0.0.1-SNAPSHOT.jar"]