FROM java:8
EXPOSE 8984
ADD /target/fhir-patient-client-service-0.0.1-SNAPSHOT.jar fhir-patient-client-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","fhir-patient-client-service-0.0.1-SNAPSHOT.jar"]