version: '2'
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
    kafka:
        image: confluentinc/cp-kafka:latest
        container_name: kafka
        ports:
          - "9092:9092"
        environment:
           KAFKA_BROKER_ID: 1
           KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
           KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
           KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
           KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
           KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        depends_on:
          - zookeeper
    discovery-server:
        image: discovery-server
        ports:
            - "8761:8761"
        restart: on-failure
    hapi-fhir-jpaserver:
        image: hapi-fhir-jpaserver
        restart: on-failure
        ports:
        - "8982:8982"    
    patient-service:
        image: patient-service
        ports:
            - "8984:8984"
        depends_on:
            - discovery-server
            - kafka
        restart: on-failure
        environment:
             SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    practitioner-service:
        image: practitioner-service
        ports:
            - "8983:8983"
        depends_on:
            - discovery-server
            - kafka
        restart: on-failure
        environment:
             SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    
    